; KERNAL methods
SETLFS = $FFBA
OPEN = $FFC0
SETNAM = $FFBD
READST = $FFB7
CHKOUT = $FFC9
CHROUT = $FFD2
CHKIN = $FFC6
CHRIN = $FFCF
PLOT = $FFF0
GETIN = $FFE4
SETMSG = $FF90
CLOSE = $FFC3
PLOT = $FFF0
SCINIT = $FF81
CLRCHN = $FFCC
RSSTAT = $0297
RDTIM = $FFDE

; rs232 buffer pointers
RS232_INBUF_PTR = $00F7
RS232_OUTBUF_PTR = $00F9

; Colors
COLOR_WHITE = 5
COLOR_GREEN = 30
COLOR_LIGHT_BLUE = $9A